const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const repo=path.resolve(__dirname,'../..'),ts=require(path.join(repo,'backend/node_modules/typescript'));
const inventory=require(path.join(repo,'backend/src/scripts/data/eurofit-hardware.json')),previous=require(path.join(repo,'backend/src/scripts/data/eurofit-hardware-v1-hashes.json'));
async function test(corrupt=false){let writes=0;const category={id:'hardware',name:'Cabinet Hardware'};const stored=inventory.products.map(p=>({id:p.id,handle:p.id,status:'published',title:'Old Cabinet name',metadata:{supplier_sku:p.supplier_sku,brand:'Eurofit Canada',model_sha256:previous[p.id],preserve_me:'yes'}}));
const svc={listProductCategories:async(q,config)=>config?.select?.includes("name")?[category]:[{id:category.id}],listProducts:async q=>stored.filter(p=>p.handle===q.handle),updateProductCategories:async(id,data)=>{writes++;Object.assign(category,data)},updateProducts:async(id,data)=>{writes++;Object.assign(stored.find(p=>p.id===id),data)}};
const sandbox={exports:{},Buffer,process:{env:{EUROFIT_APPLY:'1'}},AbortSignal,fetch:async url=>{let bytes=fs.readFileSync(path.join(repo,'storefront/public',new URL(url).pathname));if(corrupt)bytes[100]^=1;return{ok:true,arrayBuffer:async()=>bytes}},require:id=>{if(id==='@medusajs/framework/utils')return{ContainerRegistrationKeys:{LOGGER:'logger'},Modules:{PRODUCT:'product'},ProductStatus:{PUBLISHED:'published'}};if(id==='./data/eurofit-hardware.json')return inventory;if(id==='./data/eurofit-hardware-v1-hashes.json')return previous;return require(id)}};
vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(repo,'backend/src/scripts/update-eurofit-hardware-v2.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,sandbox);
const container={resolve:k=>k==='logger'?{info:()=>{}}:svc};if(corrupt){await assert.rejects(()=>sandbox.exports.default({container}),/Wrong asset/);assert.equal(writes,0);return}
await sandbox.exports.default({container});assert.equal(writes,408);assert.equal(category.name,'Hardware');assert(stored.every(p=>!p.title.includes('Cabinet')&&p.metadata.preserve_me==='yes'));assert.equal(stored.filter(p=>p.metadata.model_version===2).length,37);await sandbox.exports.default({container});assert.equal(writes,408);console.log('PASS revision: 407 titles, 37 models, Hardware category, preserves metadata, rerun zero writes, corrupt asset zero writes');}
(async()=>{await test(true);await test()})().catch(e=>{console.error(e);process.exitCode=1});
